version: '1'

services:
  # S3 compatible storage using MinIO
  s3:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./s3/data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  # Flask application for data processing
  data_processor:
    build:
      context: ./data_processor
    ports:
      - '5001:5001'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=sales_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sales_data
      - S3_ENDPOINT=http://s3:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_REGION=us-east-1
      - S3_BUCKET=sales-reports
    depends_on:
      - s3
      - mysql

  # MySQL database for data storage
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sales_data
      MYSQL_USER: sales_user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

networks:
  default:
    name: etl_network

